### ISSUE TITLE
Back button on Oculus Go controller always crashes the app

### ISSUE THREAD

**Issue by Thaurin** [polygraphene/ALVR#20]
When the back button on the Oculus Go controller is pressed, it will always crash the app. This behavior was also present in the 1.7 version that I tested.

**Comment by polygraphene** [comment]
Did you try the new releases?
v1.8 may solve this issue.

**Comment by Thaurin** [comment]
I just tried 1.9.1 and it has trouble finding my Oculus Go. The Go app stays on "Click connect" but when I click it, nothing changes.

**Comment by polygraphene** [comment]
Can you run the command `adb shell ping -c 5 (IPAddress of PC)`?
It may be a network issue.

**Comment by Thaurin** [comment]
I ran the command and I got a ping back, so I tried again on my PC. This time it worked, so maybe it was a temporary network issue or I did something wrong.

In any case, the back button still exists the game immediately and returns to the Oculus Go Home screen. I'm not sure if this is expected behaviour or if it crashes.

**Comment by polygraphene** [comment]
I have the same issue sometimes (1-2 times per day). And I can recover this by a ping command everytime.
I think that temporary network failure is caused by my Wi-Fi router. But I have not found the solution yet.

Current back button behaviour is the expected one.
But it might be a wrong behaviour for a normal Oculus Go app as you say.
I will recheck it.

Thank you!

**Comment by Thaurin** [comment]
The expected behavior on Oculus Go is that in something like your main menu, the back button takes you to the Home screen with a Quit / Back to app option. When you're not in the main menu, I've normally not seen the back button go to the Home screen immediately, but function more like an Escape key, where is cancels out to the previous or main menu.

You can close this issue if you feel like it and consider this a planned feature, or something.

P.S. I'm not sure where I can post this, so I'll add this here. I've been happily testing SteamVR games and experiences and I could write something up about what games work well with a gamepad or mouse/keyboard and which don't. I've found that many require Vive/Rift controllers, but some don't and the experience with those games is pretty flawless!

**Comment by polygraphene** [comment]
Thank you!
I've fixed the back button action in a new release.

>P.S. I'm not sure where I can post this, so I'll add this here....

Great!
Testing for various games is welcome!
You can write the test result in a separate issue or [Wiki](https://github.com/polygraphene/ALVR/wiki).

**Comment by Thaurin** [comment]
Great, I'm not sure if I could create a new Wiki page before, but I went ahead and created [a list of tested VR games](https://github.com/polygraphene/ALVR/wiki/List-of-tested-VR-games-and-experiences). Enjoy!

**Comment by polygraphene** [comment]
Thank you for useful information!
I added a link to the wiki page on README.

**Comment by Thaurin** [comment]
Great job on the back button and reconnect functionality! Two very annoying bugs solved! I still get a black screen and hanging Oculus Go (reboot required) sometimes. I'll try to pinpoint it down and create a new issue for it.

I think there is also still more functionality that can be implemented for the back button. It seems that there is an overlay in SteamVR that I sometimes get, but I can't click anything on it.

**Comment by zbendefy** [comment]
I had an issue like this where bluetooth and wifi interfered on the 2.4ghz channel. I solved it by using 5ghz wifi. But using a different wifi channel or disabling the bluetooth controller could work as well.
